### ISSUE TITLE
DLL load failed while importing sip

### ISSUE THREAD

**Issue by 0xE9DEADBEEF** [danigargu/deREferencing#13]
on IDA PRO 7.4.191112, Windows 10 with only python 3.8.2 installed, I have this error in output window on starting IDA x86/x64 : 
```
C:\Program Files\IDA Pro 7.4\python\3\idc.py:5121: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if newtype is not '':
C:\Program Files\IDA Pro 7.4\plugins\dereferencing.py: DLL load failed while importing sip: The specified module could not be found.
Traceback (most recent call last):
  File "C:\Program Files\IDA Pro 7.4\python\3\ida_idaapi.py", line 593, in IDAPython_ExecScript
    exec(code, g)
  File "C:/Program Files/IDA Pro 7.4/plugins/dereferencing.py", line 14, in <module>
    from dereferencing.views import *
  File "C:/Program Files/IDA Pro 7.4/plugins\dereferencing\views\__init__.py", line 8, in <module>
    from dereferencing.views.registers import RegsFlagsViewer
  File "C:/Program Files/IDA Pro 7.4/plugins\dereferencing\views\registers.py", line 12, in <module>
    from PyQt5 import QtGui, QtCore, QtWidgets
ImportError: DLL load failed while importing sip: The specified module could not be found.
```

**Comment by danigargu** [comment]
Hi. I think the problem is related to python 3.8: https://www.hexblog.com/?p=1402
Have you tried with python 3.7?

**Comment by 0xE9DEADBEEF** [comment]
You're right ! 👍  With Python3.7 your beautiful plugin work.
