### ISSUE TITLE
Can't read registers

### ISSUE THREAD

**Issue by pandasauce** [danigargu/deREferencing#2]
Using gdbserver, IDA 7.3 and a x86_64-bit ELF binary, I can't get the plugin registers window to load. It gets initialized with zeros for everything but RSP and RIP:

```
*RAX 0000000000000000
*RBX 0000000000000000
*RCX 0000000000000000
*RDX 0000000000000000
*RDI 0000000000000000
*RSI 0000000000000000
*R8  0000000000000000
*R9  0000000000000000
*R10 0000000000000000
*R11 0000000000000000
*R12 0000000000000000
*R13 0000000000000000
*R14 0000000000000000
*R15 0000000000000000
*RBP 0000000000000000
*RSP 00007FFFFFFFDAE0 (MEMORY)
*RIP 00007FFFF7DD6090 (MEMORY) -> mov rdi, rsp
*EFL 0000000000000200
```

The following errors are in the output window:

```
IDAPython: Error while calling Python callback <OnCreate>:
Traceback (most recent call last):
  File "C:/ida73/plugins\dereferencing\views\registers.py", line 374, in OnCreate
    self.PopulateForm()
  File "C:/ida73/plugins\dereferencing\views\registers.py", line 424, in PopulateForm
    self.reload_view()
  File "C:/ida73/plugins\dereferencing\views\registers.py", line 383, in reload_view
    self.flags_view.reload_info()
  File "C:/ida73/plugins\dereferencing\views\registers.py", line 307, in reload_info
    value = idc.GetRegValue(flag)
  File "C:\ida73\python\idc_bc695.py", line 88, in GetRegValue
    def GetRegValue(name): return get_reg_value(name)
  File "C:\ida73\python\idc.py", line 5656, in get_reg_value
    return ida_dbg.get_reg_val(name)
  File "C:\ida73\python\ida_dbg.py", line 3813, in get_reg_val
    return _ida_dbg.get_reg_val(*args)
Exception: Failed to retrieve register value
```

**Comment by danigargu** [comment]
Curious! You have tried using `linux_server64` from IDA Pro? 
With this it did not give me any problem, I will review it anyway

Thx!

**Comment by pandasauce** [comment]
Indeed, works fine with `linux_server64`. Also seems to visually work fine if I terminate and restart the process from IDA when using GDB server, but throws the following into the output window:

```
Exception in ida_dbg.DBG_Hooks dispatcher function: SWIG director method error. Error detected when calling 'DBG_Hooks.dbg_bpt'
Traceback (most recent call last):
  File "C:/ida73/plugins\dereferencing\dbg.py", line 73, in dbg_bpt
    self.notify()
  File "C:/ida73/plugins\dereferencing\dbg.py", line 41, in notify
    self.callback()
  File "C:/ida73/plugins\dereferencing\views\registers.py", line 383, in reload_view
    self.flags_view.reload_info()
  File "C:/ida73/plugins\dereferencing\views\registers.py", line 307, in reload_info
    value = idc.GetRegValue(flag)
  File "C:\ida73\python\idc_bc695.py", line 88, in GetRegValue
    def GetRegValue(name): return get_reg_value(name)
  File "C:\ida73\python\idc.py", line 5656, in get_reg_value
    return ida_dbg.get_reg_val(name)
  File "C:\ida73\python\ida_dbg.py", line 3813, in get_reg_val
    return _ida_dbg.get_reg_val(*args)
Exception: Failed to retrieve register value
```

**Comment by danigargu** [comment]
It seems that there are some flags that cannot be retrieved using gdbserver as backend.
Can you try now?
