### ISSUE TITLE
IDA 7.4 support

### ISSUE THREAD

**Issue by williballenthin** [danigargu/deREferencing#4]
When loading deREferencing into an IDA 7.4 + py3 session, I encounter the following stack trace:

```
Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.4/plugins/dereferencing.py", line 39, in activate
    w = RegsFlagsViewer()
  File "C:/Program Files/IDA Pro 7.4/plugins\dereferencing\views\registers.py", line 373, in __init__
    dbg.initialize()
  File "C:/Program Files/IDA Pro 7.4/plugins\dereferencing\dbg.py", line 207, in initialize
    m.get_ptr = idc.Dword
AttributeError: module 'idc' has no attribute 'Dword'
Traceback (most recent call last):
  File "C:/Program Files/IDA Pro 7.4/plugins/dereferencing.py", line 45, in activate
    w = StackViewer()
  File "C:/Program Files/IDA Pro 7.4/plugins\dereferencing\views\stack.py", line 24, in __init__
    dbg.initialize()
  File "C:/Program Files/IDA Pro 7.4/plugins\dereferencing\dbg.py", line 207, in initialize
    m.get_ptr = idc.Dword
AttributeError: module 'idc' has no attribute 'Dword'
```

**Comment by danigargu** [comment]
For now, it is not compatible with IDA 7.4 + py3.
I will try to support it as soon as I have time.

Thanks!

**Comment by danigargu** [comment]
Done at #8
Thanks Willy!
